### ISSUE TITLE
no-gen-subtitle not working

### ISSUE THREAD

**Issue by autoditactics** [dxing97/subs2cia#16]
The `--no-gen-subtitle` option given in the README doesn't seem to work. I'm getting the following error.
`subs2cia: error: unrecognized arguments: --no-gen-subtitle`

OS: MacOS Mojave

**Comment by dxing97** [comment]
It's only available in the dev/master branch, hopefully will be pushed to pypi soon when the next version number is out, probably when I finalize the -RR feature.

In the meantime, you can install the latest commit from GitHub to get `--no-gen-subtitle` working.

**Comment by autoditactics** [comment]
Thanks. Appreciated.

**Comment by dxing97** [comment]
0.3.3 is now out and includes `--no-gen-subtitle`
