### ISSUE TITLE
Can't run main.py directly

### ISSUE THREAD

**Issue by KieranBrannigan** [dxing97/subs2cia#2]
I didn't feel like installing with pip, so I tried running main.py directly by navigating to the subs2cia directory and running: `python main.py` but I got this error:
```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from subs2cia.argparser import get_args_subs2cia
ModuleNotFoundError: No module named 'subs2cia'
```

I'm not familiar with writing packages for python, but it seems like you're importing argparser from subs2cia as though it is an installed package, from within the package. Maybe a fix would be within the package just do a relative import? Although I know there is some funny business when it comes to python, packages and  imports.

I'll just install with pip now but thought I would mention this.

**Comment by dxing97** [comment]
I'm able to reproduce this if the pip package isn't installed, let me see if I can figure out a fix.

**Comment by dxing97** [comment]
Fixed with a relative import in main.py
