### ISSUE TITLE
Error when using SRS command

### ISSUE THREAD

**Issue by matsumurae** [dxing97/subs2cia#27]
**Error**
`Traceback (most recent call last):`
`  File "/usr/local/bin/subs2cia", line 5, in <module>`
`    from subs2cia.cli import main`
`  File "/usr/local/lib/python3.9/site-packages/subs2cia/__init__.py", line 1, in <module>`
`    from subs2cia import main`
`  File "/usr/local/lib/python3.9/site-packages/subs2cia/main.py", line 11, in <module>`
`    from subs2cia.CardExport import CardExport`
`  File "/usr/local/lib/python3.9/site-packages/subs2cia/CardExport.py", line 10, in <module>`
`    import pandas as pd`
`  File "/usr/local/lib/python3.9/site-packages/pandas/__init__.py", line 16, in <module>`
`    raise ImportError(`
`ImportError: Unable to import required dependencies:`
`numpy: No module named 'numpy'`

**Why I use it**
I'm trying to use it with audio + subs. I have a lot of Audio Drama's and I want them to be Anki cards.

**How I use it**
- I've tried with `.mp3` and `.mp4` and both happened the same.
- I'm using `.ass` subs.
- I'm using Mac OS Monterey 12.5.1 (Not M1)

**Commands I've tried**
`subs2cia srs -i file.mp3 subs.ass`
`subs2cia srs -i file.mp3`
`subs2cia srs -i file.mp3 subs.ass -d srs_export -p 100 -N`
`subs2cia srs -i video.mp4`
`subs2cia srs -i video.mp4 subs.ass`
`subs2cia srs -i video.mp4 subs.ass -d srs_export -p 100 -N`

**Notes**
- I've used `condense` without errors.
- The `.ass` file was generated with Aegisub using the `.mp3` file. This was done by hand, not using speech detection (cause it's japanese).

**Comment by dxing97** [comment]
Looks like you need to install numpy. `pip install numpy` should do the trick.

**Comment by kanjieater** [comment]
I can confirm I do not have numpy installed, installed the tool today, and it is working now for the latest version.

**Comment by dxing97** [comment]
Great!
